### ISSUE TITLE
Projekterstellung funktioniert nicht unter Linux

### ISSUE THREAD

**Issue by frankbroniewski** [Geoportail-Luxembourg/qgis-pag-plugin#120]
Hi,

unter Linux schlägt die Projekterstellung fehl:

> Traceback (most recent call last):
  File "/home/frank/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PagLuxembourg/widgets/create_project/create_project_dialog.py", line 100, in accept
    PagLuxembourg.main.current_project.create(folder,name)
  File "/home/frank/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PagLuxembourg/project.py", line 117, in create
    self._updateDatabase()
  File "/home/frank/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PagLuxembourg/project.py", line 270, in _updateDatabase
    conn = self._getDbConnection()
  File "/home/frank/.local/share/QGIS/QGIS3/profiles/default/python/plugins/PagLuxembourg/project.py", line 711, in _getDbConnection
    conn.load_extension('/Library/Frameworks/SQLite3.framework/Versions/E/Modules/mod_spatialite.dylib')
sqlite3.OperationalError: /Library/Frameworks/SQLite3.framework/Versions/E/Modules/mod_spatialite.dylib.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

Wenn man sich den Code dazu [ansieht](https://github.com/Geoportail-Luxembourg/qgis-pag-plugin/blob/44e943c2eb6111cbddaca0ecb92a9da261e25def/project.py#L706), ist das auch kein Wunder, hier wird nur Windows und Macos behandelt.

Wenn man den Code durch 
```
        try:
            conn = utils.spatialite_connect(self.database)
        except:
            conn = sqlite3.connect(self.database)
            conn.enable_load_extension(True)
            conn.load_extension('/Library/Frameworks/SQLite3.framework/Versions/E/Modules/mod_spatialite.dylib')
```
ersetzt, bekommt man das Plugin auch unter Linux ans Laufen. Keine Ahnung, ob der Code für den Mac überhaupt notwendig ist, `utils.spatialite` führt schon Tests durch, um das dynamische Laden des Spatialite-Moduls sicherzustellen. Und der fest eingestellte Pfad sieht mir auch eher nach Ärger aus ... allerdings kann ich das ohne einen Mac auch nicht nachprüfen

**Comment by jaykayone** [comment]
Unter MacOS funktionniert es gut, und Linux war bis jetzt nie eine Anforderung.
Wenn dein Fix funktionniert, würde ich dich bitten, eine PR zu machen, wir haben selbst kein QGIS auf Linux, mit dem wir testen könnten

**Comment by frankbroniewski** [comment]
> Linux war bis jetzt nie eine Anforderung
Homeoffice macht es möglich ...
ich teste meinen Vorschlag noch bei Gelegenheit unter Windows und schicke euch den PR, ob es weiterhin unter MacOS funktioniert muss ich leider euch überlassen mangels passender Hardware
