### ISSUE TITLE
Ne fonctionne pas sur mac

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#20]
```
Couldn't load plugin PAGLuxembourg due to an error when calling its classFactory() method


Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ity425/.qgis2/python/plugins/PAGLuxembourg/__init__.py", line 34, in classFactory
    from main import PAGLuxembourg
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ity425/.qgis2/python/plugins/PAGLuxembourg/main.py", line 30, in 
    from widgets.create_project.create_project import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ity425/.qgis2/python/plugins/PAGLuxembourg/widgets/create_project/create_project.py", line 9, in 
    from create_project_dialog import CreateProjectDialog
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ity425/.qgis2/python/plugins/PAGLuxembourg/widgets/create_project/create_project_dialog.py", line 30, in 
    import PagLuxembourg.main
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named PagLuxembourg.main


Python version:
2.7.10 (default, Jul 14 2015, 19:46:27) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]


QGIS version:
2.8.1-Wien Wien, 

Python path: ['/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Applications/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/ity425/.qgis2/python', u'/Users/ity425/.qgis2/python/plugins', '/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/C/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/matplotlib-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', u'/Users/ity425/.qgis2//python', '/Applications/QGIS.app/Contents/Resources/python/plugins/fTools/tools']
```

**Comment by jaykayone** [comment]
c'était de ma faute, le plugin doit s'appeler "PagLuxembourg" et pas "PAGLuxembourg"
