### ISSUE TITLE
error importing shape file

### ISSUE THREAD

**Issue by jaykayone** [Geoportail-Luxembourg/qgis-pag-plugin#48]
```
An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/ity425/.qgis2/python/plugins/PagLuxembourg/widgets/import_data/import_shp_dialog.py", line 326, in _launchImport
    imported_extent = self._importLayer(self.shplayer, qgis_layer, self._getMapping())
  File "/Users/ity425/.qgis2/python/plugins/PagLuxembourg/widgets/import_data/importer.py", line 88, in _importLayer
    QCoreApplication.translate('Importer','Commit error on layer {}').format(qgis_layer.name()))
NameError: global name 'qgis_layer' is not defined
```

**Comment by jaykayone** [comment]
```
[{"FieldMapping": [["FID_", "", null, false], ["Entity", "", null, false], ["Handle", "", null, false], ["Layer", "", null, false], ["Zone_proje", "", null, false], ["Label", "", null, false], ["Area", "", null, false], ["Ortschaft", "", null, false], ["Label2011", "", null, false], ["Z_proj2011", "", null, false], ["Label_AP1", "CATEGORIE", null, true]], "DestinationLayerName": "PAG.ZONAGE", "SourceLayerName": null, "Enabled": false, "SourceLayerFilter": null, "Valid": false}]
```

**Comment by jaykayone** [comment]
https://download.geoportail.lu/public.php?service=files&t=5b9519ff42e350f6e02473f6c551a047&download

**Comment by arx-it** [comment]
Corrigé.
Je pense que ca vient d'une géométrie nulle, et que faire dans ce cas?
