### ISSUE TITLE
Migration QGIS 2.14

### ISSUE THREAD

**Issue by arx-it** [Geoportail-Luxembourg/qgis-pag-plugin#93]

**Comment by arx-it** [comment]
Bug sur l'outil topoclean

**Comment by arx-it** [comment]
Bug sur l'outil Topoclean (produit sur n'importe quelle couche d'un projet PAG) :

Traceback (most recent call last):
              File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean_dialog.py", line 53, in _launchCleaning
                self.topoclean.cleanLayer(self.layer, self.sbThreshold.value())
              File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\topoclean\topoclean.py", line 69, in cleanLayer
                vclean_layer = QgsVectorLayer(result['output'], 'VClean', 'ogr')
            TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by arx-it** [comment]
Bug en important un DXF, en sélectionnant les mêmes « QGIS Layer » que dans l’aide :

TypeError: QDoubleSpinBox.setMinimum(float): argument 1 has unexpected type 'unicode' 
Traceback (most recent call last):
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 210, in _tabLayersMappingCellChanged
    self._loadCurrentFieldMapping()
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 326, in _loadCurrentFieldMapping
    self.tabFieldsMapping.setCellWidget(rowindex, 1, self._getFieldsMappingTableItemWidget(qgis_layer, field.name(), constant_value)) # Constant value
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 336, in _getFieldsMappingTableItemWidget
    return self._getSpinbox(config['Min'], config['Max'], config['Step'], config['AllowNull'], value)
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 443, in _getSpinbox
    spinbox.setMinimum(minvalue)
TypeError: QDoubleSpinBox.setMinimum(float): argument 1 has unexpected type 'unicode'

J’ai l’impression que le bug se produit sur la couche « COULOIRS_ET_ESP_RES ».
Ensuite, autre bug se produit, en passant d’une ligne à une autre (lors d'un clic sur une ligne de l'outil) :
Traceback (most recent call last):
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 207, in _tabLayersMappingCellChanged
    self._updateMappingFromUI(previousRow)
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\import_dxf_dialog.py", line 365, in _updateMappingFromUI
    enabled = self._getCellValue(self.tabFieldsMapping, field_rowindex, 2)
  File "C:/Users/arxit/.qgis2/python/plugins\PagLuxembourg\widgets\import_data\importer.py", line 555, in _getCellValue
    for child in widget.children():
AttributeError: 'NoneType' object has no attribute 'children'
